### ISSUE TITLE
RuntimeError: Token س not found and default index is not set

### ISSUE THREAD

**Issue by MahtaFetrat** [sajadalipour7/Persian-Grapheme-To-Phoneme-With-Transformer#1]
I tried to test this Grapheme to Phoneme model with a minimal `data.csv` only with the word `'سلام'` in [this](https://colab.research.google.com/drive/1QGMHfBqfhW_yaw1t8Fg-ILHgs0yJ1CG_?usp=sharing) notebook. But the following line of code
```python
inference(g2p_model,"سلام").replace(" ","")
```
Raises the following error

> RuntimeError: Token س not found and default index is not set

Can you please help me with that?

**Comment by sajadalipour7** [comment]
Hi. I should have uploaded my vocab object too. here is the link: https://drive.google.com/file/d/1bxoEMM7f2TdNGX_jtv_R-U-RzpWfTedb/view?usp=sharing

Now replace the following:
```
for ln in [SRC_LANGUAGE, TGT_LANGUAGE]:
    # Training data Iterator
    all_iter=all_data
    # Create torchtext's Vocab object
    vocab_transform[ln] = build_vocab_from_iterator(yield_tokens(all_data, ln),
                                                    min_freq=1,
                                                    specials=special_symbols,
                                                    special_first=True)
```
with this:
```
vocab_transform = torch.load("vocab.pt")
```

**Comment by MahtaFetrat** [comment]
Thank you for the quick and detailed response. It was really helpful!
